OPENFST_DIR = $(THIRDPARTY_DIR)/openfst
OPENFST_LIB_DIR = $(OPENFST_DIR)/lib
OPENFST_INC_DIR = $(OPENFST_DIR)/include

RE2_DIR = $(THIRDPARTY_DIR)/re2
RE2_LIB_DIR = $(RE2_DIR)/obj
RE2_INC_DIR = $(RE2_DIR)

OPTIMIZATION_FLAGS = -O3
CXXFLAGS_  = $(CXXFLAGS) $(OPTIMIZATION_FLAGS) -Wall -I. -Isrc -I$(THIRDPARTY_DIR) -I$(RE2_INC_DIR) -I$(OPENFST_INC_DIR)
LDFLAGS_ = $(LDFLAGS) $(OPTIMIZATION_FLAGS) -L$(OPENFST_LIB_DIR) -L$(RE2_LIB_DIR) -lre2 -lfst -lfte

OBJ_REGEX2DFA = src/regex2dfa.o
TARGET_REGEX2DFA = bin/regex2dfa

TARGET_LIBRE2 = $(RE2_LIB_DIR)/libre2.a
$(TARGET_REGEX2DFA): $(TARGET_LIBRE2) $(TARGET_LIBOPENFST) $(OBJ_REGEX2DFA)
	$(CXX) $(CXXFLAGS_) $(LDFLAGS_) $(OBJ_REGEX2DFA) -o $@

$(TARGET_LIBGTEST):
	cd $(GTEST_DIR) && $(MAKE)

$(TARGET_LIBRE2):
	cd $(RE2_DIR) && $(MAKE) obj/libre2.a
