THIRDPARTY_DIR = third_party

FST_DIR = $(THIRDPARTY_DIR)/openfst

RE2_DIR = $(THIRDPARTY_DIR)/re2
RE2_LIB_DIR = $(RE2_DIR)/obj
RE2_INC_DIR = $(RE2_DIR)

OPTIMIZATION_FLAGS = -O3
CXXFLAGS_  = $(CXXFLAGS) $(OPTIMIZATION_FLAGS) -Wall -I. -Isrc -I$(THIRDPARTY_DIR) -I$(RE2_INC_DIR)
LDFLAGS_ = $(LDFLAGS) $(OPTIMIZATION_FLAGS) -L$(RE2_LIB_DIR) -lre2

OBJ_REGEX2DFA = src/regex2dfa.o

TARGET_REGEX2DFA = bin/regex2dfa
TARGET_LIBRE2 = $(RE2_LIB_DIR)/libre2.a

$(TARGET_REGEX2DFA): $(TARGET_LIBRE2) $(OBJ_REGEX2DFA)
	$(CXX) $(CXXFLAGS_) $(LDFLAGS_) $(OBJ_REGEX2DFA) -o $@

$(TARGET_LIBRE2):
	cd $(RE2_DIR) && $(MAKE) obj/libre2.a

%.o: %.cc
	$(CXX) $(CXXFLAGS_) -c -o $@ $<

clean:
	cd $(FST_DIR) && $(MAKE) clean
	cd $(RE2_DIR) && $(MAKE) clean
	rm -f $(TARGET_REGEX2DFA)
